color: green
fieldLayouts:
  76b1aee7-cde3-4114-af90-49e88a21ab8c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 68a24a5b-c943-450d-9a28-b7971ab2d45d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 746d4468-0766-4f3d-bb17-5f3c7495ab8f # Images
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 601d5a26-ef84-45d2-9781-4f991b80c2c7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5cba4a2e-7a48-4ff6-b0d6-82e08040de06
        userCondition: null
handle: images
hasTitleField: true
icon: image
name: Images
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
