color: green
fieldLayouts:
  0cf09ae8-e276-4a70-9520-52b2520eea4a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 49b471fa-34ea-43b8-b207-cfd9bca17d93
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a5dee1a3-acf4-4a0f-9f42-0768e071b785 # Date
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ff547550-35ab-49cd-b54b-98b4c72c0859
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9a2f52fa-7fd4-4829-a714-10034e405d6c # Expertise
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1d92fc25-6e84-4264-a4c3-3ab139bb35ec
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b2c49af5-fc90-4ae9-af7a-adb9ef6d0a06 # Thumbnail
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: acf6e9a5-e7ae-4725-a101-1f736d578ea8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 62e4fc27-9b65-4cb4-aa7b-2ca37a30ac90 # Skills
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 00a3ee1a-f6d0-4213-b9c4-9eb6f779e379
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 115a7e48-bc3d-4fc6-bb67-0240a8eb88f6 # Text Alinea
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7cf4494a-ba22-4b23-87cd-1eb6d6b238bd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a34a85ee-a035-4936-8703-75bba665b387 # Text
            handle: f_linkText
            includeInCards: false
            instructions: null
            label: 'Link Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0d2f6a43-1011-43b3-836c-b2df6de518e1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5c72c7b2-7a1c-4edf-8b98-a0f2bc44148e # Link
            handle: null
            includeInCards: false
            instructions: null
            label: Link
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ffd8f372-c556-4f7c-91b5-da69f628ef03
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e955d983-a1bd-4ff8-b0ad-58cb9ed52daa # Assets
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 870cb38a-7cf1-45f9-a089-f197c7d44f17
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7310b12c-2afc-49ec-aa59-976514352240
        userCondition: null
handle: work
hasTitleField: true
icon: folder
name: Work
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
