altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  e37691bc-0166-4ad4-adcc-b9f65b61045c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: ce634c81-bd1d-4edb-b4da-0287a5c36c98
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 14710fc0-8610-4cd8-b79a-1b4cccb0a9e2
        userCondition: null
fs: icons
handle: icons
name: Icons
sortOrder: 2
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: $ICONS_PATH_TRANSFORMS
