altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  4183a7de-1a35-432e-8c7f-0a4ddde7d267:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: ae6e3835-c45e-4c3f-b21b-83e02a16b139
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 612a7473-1e21-48da-b7fa-d69964789c65
        userCondition: null
fs: videos
handle: video
name: Video
sortOrder: 3
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: $VIDEOS_PATH_TRANSFORMS
