columnSuffix: null
handle: f_socials
instructions: null
name: Socials
searchable: false
settings:
  createButtonLabel: null
  entryTypes:
    - 5a789c66-a838-4ee6-bac8-09c7df998fb7 # Socials
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
