columnSuffix: null
handle: f_social
instructions: null
name: Social
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - Instagram
        -
          - value
          - instagram
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Vimeo
        -
          - value
          - vimeo
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - LinkedIn
        -
          - value
          - linkedin
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Github
        -
          - value
          - github
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Youtube
        -
          - value
          - youtube
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
