dateModified: 1713364815
email:
  fromEmail: claudinedekesel@hotmail.com
  fromName: Uclicked
  transportType: craft\mail\transportadapters\Sendmail
fs:
  icons:
    hasUrls: true
    name: Icons
    settings:
      path: $ICONS_PATH
    type: craft\fs\Local
    url: $ICONS_URL
  images:
    hasUrls: true
    name: Images
    settings:
      path: $IMAGES_PATH
    type: craft\fs\Local
    url: $IMAGES_URL
  videos:
    hasUrls: true
    name: 'Video''s'
    settings:
      path: $VIDEOS_PATH
    type: craft\fs\Local
    url: $VIDEOS_URL
meta:
  __names__:
    0a5f20a3-628b-45b5-be87-cc02bac4e750: Images # Images
    4b96d956-e446-4be1-9b4f-fa85cfbd3d69: Tags # Tags
    5a789c66-a838-4ee6-bac8-09c7df998fb7: Socials # Socials
    5c72c7b2-7a1c-4edf-8b98-a0f2bc44148e: Link # Link
    5fabca4f-259c-4561-9900-33030a68bb33: 'Public Schema' # Public Schema
    08eecd62-2726-47c3-bf5d-2ad4554e1430: Icon # Icon
    9a2f52fa-7fd4-4829-a714-10034e405d6c: Expertise # Expertise
    9de98acf-fd0c-4c36-b467-aa47165cb77d: Skills # Skills
    26f1a557-d446-47f2-a573-7e9d972187c5: Home # Home
    40f0a45c-ba73-4bf6-8fc8-38dc129b0bd3: 'Regular text' # Regular text
    62d960e2-6af4-4389-95c3-b7b5f093e6ce: Images # Images
    62e4fc27-9b65-4cb4-aa7b-2ca37a30ac90: Skills # Skills
    83eb9800-527f-416b-901d-5c800fc04bc7: Video # Video
    93eee091-ad6a-4c3c-befc-5967775858e5: Uclicked # Uclicked
    115a7e48-bc3d-4fc6-bb67-0240a8eb88f6: 'Text Alinea' # Text Alinea
    216ed538-45c5-465b-8945-011833aac1c8: Icons # Icons
    746d4468-0766-4f3d-bb17-5f3c7495ab8f: Images # Images
    1959c29e-73fd-4e22-9902-be38ade8a5c3: icon # icon
    6286d3b4-4c71-4a92-a574-bde6cb5f2ab9: Expertises # Expertises
    8281cc9c-885e-4b2b-af1f-69d467ab438e: Contact # Contact
    8553c2b6-879a-4c56-86b3-46f82e3b9789: Simple # Simple
    51990cb1-d5ed-418b-95bb-07ca6d6e258e: Work # Work
    a5dee1a3-acf4-4a0f-9f42-0768e071b785: Date # Date
    a34a85ee-a035-4936-8703-75bba665b387: Text # Text
    a2274db0-64ad-4f59-9623-a3412077c5c5: Uclicked # Uclicked
    b2c49af5-fc90-4ae9-af7a-adb9ef6d0a06: Thumbnail # Thumbnail
    b9eea2eb-7da2-4fab-b84e-19a1fca5a9a5: About # About
    c2986554-79d7-43b3-998b-4a718c4b07f7: Hero # Hero
    ca146faa-4b2a-46e3-9141-cfb9d9dffeba: Video # Video
    cbc80322-2253-48cd-adad-4ec8f633b2f8: Socials # Socials
    cec63c16-d6e9-41b6-9c34-4dceaa7f2c07: Skills # Skills
    d4c2549b-486f-4629-b0f8-6f340c62e6e8: Icons # Icons
    daef5396-a035-4614-b8b6-85378f80d621: Home # Home
    e54d784a-0509-430a-9623-1c11f99cfed1: Contact # Contact
    e955d983-a1bd-4ff8-b0ad-58cb9ed52daa: Assets # Assets
    ecaac4e5-f553-46ec-a0c0-906661a87adc: Expertises # Expertises
    ee062bb8-9e99-418e-b265-d5d174a15317: Email # Email
    eea874d8-2eb3-40ac-bb62-2eb01772fec2: Work # Work
    f18e2668-3f92-4c4a-b4c0-dffe8f4c373a: Socials # Socials
    f7440752-7251-4605-907b-7a296c79cdf5: Video # Video
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: Uclicked
  schemaVersion: 5.0.0.20
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
