defaultPlacement: end
enableVersioning: true
entryTypes:
  - e72c7568-1a5e-4024-9e94-aa7cce27363a
handle: about
maxAuthors: 1
name: About
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  a2274db0-64ad-4f59-9623-a3412077c5c5: # Uclicked
    enabledByDefault: true
    hasUrls: true
    template: about/_entry
    uriFormat: about
type: single
