defaultPlacement: end
enableVersioning: true
entryTypes:
  - 4a24b0cb-9182-47e9-ae61-407ceefb9f63
handle: hero
maxAuthors: 1
name: Hero
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  a2274db0-64ad-4f59-9623-a3412077c5c5: # Uclicked
    enabledByDefault: true
    hasUrls: true
    template: hero/_entry
    uriFormat: hero
type: single
