defaultPlacement: end
enableVersioning: true
entryTypes:
  - cec63c16-d6e9-41b6-9c34-4dceaa7f2c07 # Skills
handle: skills
maxAuthors: 1
name: Skills
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  3bbf42b8-b5c8-43e8-8af4-b0abae578917: # Uclicked EN
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  a2274db0-64ad-4f59-9623-a3412077c5c5: # Uclicked
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: 42bfe24a-4eac-497b-a833-9fe7cd73191f
type: structure
