defaultPlacement: end
enableVersioning: true
entryTypes:
  - 51990cb1-d5ed-418b-95bb-07ca6d6e258e # Work
handle: work
maxAuthors: 1
name: Work
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  a2274db0-64ad-4f59-9623-a3412077c5c5: # Uclicked
    enabledByDefault: false
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: 9421cfdd-14f2-4236-9b6f-d4168cc4c147
type: structure
